
version: '3.8'
services:
  jenkins:
    image: jenkins/jenkins:lts
    privileged: true
    user: root
    ports:
     - "8080:8080"
     - "50000:50000"
    container_name: jenkins
    volumes:
     - "//Users//dsvitlyc//PycharmProjects//Auto_tests//_jenkins_data/jenkins_configuration:/var/jenkins_home"
     - "//Users//dsvitlyc//PycharmProjects//Auto_tests//_jenkins_datasock:/var/run/docker.sock"